/* eslint-disable @typescript-eslint/naming-convention */
export const PERMISSIONS = Object.freeze({
  APP: {
    VIEW: 'APP.VIEW',
  },
  ROLES: {
    VIEW: 'ROLES.VIEW',
    CREATE: 'ROLES.CREATE',
    EDIT: 'ROLES.EDIT',
    DELETE: 'ROLES.DELETE',
    VIEW_SCREEN: 'ROLES.VIEW_SCREEN',
    ADMINISTRATOR: 'ROLES.ADMINISTRATOR',
    MENTOR: 'ROLES.MENTOR',
    STUDENT: 'ROLES.STUDENT',
    RND: 'ROLES.RND',
  },
  MENTOR: {
    CREATE: 'MENTOR.CREATE',
    EDIT: 'MENTOR.EDIT',
    VIEW: 'MENTOR.VIEW',
    REMOVE: 'MENTOR.REMOVE',
    GET_PROFILE: 'MENTOR.GET_PROFILE',
  },
  STUDENT: {
    CREATE: 'STUDENT.CREATE',
    EDIT: 'STUDENT.EDIT',
    VIEW: 'STUDENT.VIEW',
    REMOVE: 'STUDENT.REMOVE',
  },
  COURSE: {
    CREATE: 'COURSE.CREATE',
    EDIT: 'COURSE.EDIT',
    VIEW: 'COURSE.VIEW',
    REMOVE: 'COURSE.REMOVE',
  },
  STUDENT_COURSE: {
    CREATE: 'STUDENT_COURSE.CREATE',
    EDIT: 'STUDENT_COURSE.EDIT',
    VIEW: 'STUDENT_COURSE.VIEW',
  },
  STUDENT_EDITOR: {
    CREATE: 'STUDENT_EDITOR.CREATE',
    EDIT: 'STUDENT_EDITOR.EDIT',
    VIEW: 'STUDENT_EDITOR.VIEW',
  },
  STUDENT_LESSON: {
    CREATE: 'STUDENT_LESSON.CREATE',
    EDIT: 'STUDENT_LESSON.EDIT',
    VIEW: 'STUDENT_LESSON.VIEW',
  },
  LESSON: {
    CREATE: 'LESSON.CREATE',
    EDIT: 'LESSON.EDIT',
    VIEW: 'LESSON.VIEW',
    REMOVE: 'LESSON.REMOVE',
  },
  SUPPORT: {
    CREATE: 'SUPPORT.CREATE',
    EDIT: 'SUPPORT.EDIT',
    VIEW: 'SUPPORT.VIEW',
    REMOVE: 'SUPPORT.REMOVE',
    ACCEPT: 'SUPPORT.ACCEPT',
    REJECT: 'SUPPORT.REJECT',
    FINISH: 'SUPPORT.FINISH',
    CANCEL: 'SUPPORT.CANCEL',
  },
});
